export const googleFonts = [
  "Poppins",
  "Roboto",
  "Open Sans",
  "Montserrat",
  "Lato",
  "Oswald",
  "Raleway",
  "Merriweather",
  "Playfair Display",
  "Inter",
  "Nunito",
  "Quicksand",
  "Work Sans",
  "Source Sans Pro",
  "Ubuntu",
  "Cabin",
  "Fira Sans",
  "Rubik",
  "DM Sans",
  "PT Sans",
  "Titillium Web",
  "Karla",
  "Manrope",
  "Heebo",
  "Josefin Sans",
  "Noto Sans",
  "Bebas Neue",
  "Anton",
  "Barlow",
  "Mulish",
  "Space Grotesk",
  "Urbanist",
  "Varela Round",
  "Zilla Slab",
  "Cormorant Garamond",
  "Domine",
  "Arimo",
];
